In [19]:
import numpy as np
import torch

In [31]:
# 創健tensor
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
									[[5, 6, 7], [7, 8, 9]]])
print(a.shape)
print(a)

torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])


In [38]:
# 將tensor形狀由[2,2,3]改為[2,6]
b = a.reshape(2, 6)
c = a.view(2,6)
d = a.reshape(2,-1)
print(b.shape, c.shape, d.shape)
b,c,d

torch.Size([2, 6]) torch.Size([2, 6]) torch.Size([2, 6])


(tensor([[1, 2, 3, 3, 4, 5],
         [5, 6, 7, 7, 8, 9]]),
 tensor([[1, 2, 3, 3, 4, 5],
         [5, 6, 7, 7, 8, 9]]),
 tensor([[1, 2, 3, 3, 4, 5],
         [5, 6, 7, 7, 8, 9]]))

In [41]:
e = a.permute((0, 2, 1))
f = a.transpose(1,2)
print(e.shape, f.shape)
e, f

torch.Size([2, 3, 2]) torch.Size([2, 3, 2])


(tensor([[[1, 3],
          [2, 4],
          [3, 5]],
 
         [[5, 7],
          [6, 8],
          [7, 9]]]),
 tensor([[[1, 3],
          [2, 4],
          [3, 5]],
 
         [[5, 7],
          [6, 8],
          [7, 9]]]))

In [43]:
# 增加張量維度
g = torch.unsqueeze(a, dim=1) #增加維度在1的位置
h = torch.squeeze(g) #壓縮為度為1的位置
print(g.shape, h.shape)
g, h

torch.Size([2, 1, 2, 3]) torch.Size([2, 2, 3])


(tensor([[[[1, 2, 3],
           [3, 4, 5]]],
 
 
         [[[5, 6, 7],
           [7, 8, 9]]]]),
 tensor([[[1, 2, 3],
          [3, 4, 5]],
 
         [[5, 6, 7],
          [7, 8, 9]]]))