In [49]:
import numpy as np
import torch

In [50]:
#創建tensor
x = torch.rand((2,2))
y = torch.rand((2,2))
z = torch.rand((2,2), requires_grad=True)
a = x+y
b = z+a
x,y,z,a,b

(tensor([[0.2973, 0.9311],
         [0.8770, 0.0714]]),
 tensor([[0.1484, 0.2476],
         [0.0575, 0.6214]]),
 tensor([[0.7185, 0.5685],
         [0.0034, 0.0150]], requires_grad=True),
 tensor([[0.4457, 1.1787],
         [0.9345, 0.6928]]),
 tensor([[1.1642, 1.7472],
         [0.9379, 0.7078]], grad_fn=<AddBackward0>))

In [51]:
# 查看requires_grad
print(f'x:{x.requires_grad},y:{y.requires_grad},z:{z.requires_grad}')
print(f'a: {a.requires_grad}, b: {b.requires_grad}')

x:False,y:False,z:True
a: False, b: True


In [52]:
#查看grad_fn
print(f'x: {x.grad_fn}, y: {y.grad_fn}, z: {z.grad_fn}')
print(f'a: {a.grad_fn}, b: {b.grad_fn}')

x: None, y: None, z: None
a: None, b: <AddBackward0 object at 0x15c2ff730>


In [53]:
#創建tensor
x = torch.ones((2,2), requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [54]:
#以加法創建新tensor
y = x + 2
y, y.requires_grad

(tensor([[3., 3.],
         [3., 3.]], grad_fn=<AddBackward0>),
 True)

In [55]:
z = y*y*3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [56]:
print(x.grad_fn)
print(y.grad_fn)
print(z.grad_fn)
print(out.grad_fn)

None


In [57]:
#計算微分
w = out.backward()

In [58]:
print(x.grad_fn)

None
